version: '3'
services:
    wanna-build:
        image: wanna-build
        hostname: wannadb
        privileged: true
        ports:
            - 5432:5432/tcp
        volumes:
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/11_init.sql
            - ./scripts/init.sh:/docker-entrypoint-initdb.d/12_init.sh
            - ./scripts/seed.sql:/docker-entrypoint-initdb.d/13_seed.sql
            - ./scripts/trigger.sh:/docker-entrypoint-initdb.d/14_trigger.sh
volumes:
    wb-vol:
        driver: local
