#!/usr/bin/env python3
# Copyright (c) 2018-2020 FASTEN.
#
# This file is part of FASTEN
# (see https://www.fasten-project.eu/).
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
import argparse
import csv
import networkx as nx

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("input_dot")
    parser.add_argument("output_csv")
    parser.add_argument(
        "-p", "--profile", action='store_true', help="Gprof profile"
    )
    args = parser.parse_args()
    g = nx.drawing.nx_pydot.read_dot(args.input_dot)
    with open(args.output_csv, 'w') as f:
        writer = csv.writer(f)
        edges = g.edges.data(False)
        if args.profile:
            nodes = {k: v.split('\\')[0].replace('"', '')
                    for k, v in nx.get_node_attributes(g, 'label').items()}
            edges = [(nodes[e[0]], nodes[e[1]]) for e in edges]
        writer.writerows(edges)
