#!/bin/bash
# Parameters
SRC=$1
R_OPTION_PARAM="cgraph.txt?all=1&n=p&type=1&defined=1&nodes=1"
FCAN_EXTRA_OPTIONS='-d'
TOOL='cscout'

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/base_analyzer"

build() {
    printf "\n###Debug: build\n"
    echo "tool: cscout" >> $DEST_PKG/report
    rm -rf /tmp_dir && mkdir -p /tmp_dir
    if ! CSMAKEFLAGS='-T /tmp_dir -A -s cscout_projects -k' MAKE=/usr/local/bin/csmake dpkg-buildpackage -b 2> error; then
        cp error $DEST_PKG/build.err
        echo "build: failed" >> $DEST_PKG/report
        exit -1
    else
        if [ -f "error" ]; then
            cp error $DEST_PKG/build.war
        fi
    fi
    echo "build: success" >> $DEST_PKG/report
}

cs_merge_files() {
    printf "\n###Debug: merge_cs_files\n"
    cd $TOOL_DIR
    for p in $(ls *\#*); do
        name=$(echo $p | sed 's/.*#//')
        cat $p >> $name
        rm -f $p
    done
    cd $PWD_SRC
}

run_cscout() {
    printf "\n###Debug: run_cscout\n"
    cd $TOOL_DIR
    cs_projects=$(ls)
    for cs in $cs_projects; do
        echo "Processing $cs"
        x1=$(basename -- "$cs")
        x=${x1::${#x1}-3}
        if [[ ! $USED_BINARIES == *"$x"* ]]; then
            echo "Skip $cs"
            echo "#analysis: $cs: not in USED_BINARIES" >> $DEST_PKG/report
            continue
        fi
        if [[ -f "$cs" && ! -s "$cs" ]]; then
            echo "#analysis: ${cs}: empty" >> $DEST_PKG/report
            echo "analysis: ${cs}: failed: empty" >> $DEST_PKG/report
            continue
        fi
        if cscout -R "$R_OPTION_PARAM" $cs 2>error; then
            mv cgraph.txt $TOOL_DIR/$(basename $cs .cs).txt
            if [ -f "error" ]; then
                cp error $DEST_PKG/$cs.warn
            fi
            echo "analysis: ${cs}: success" >> $DEST_PKG/report
        else
            cp error $DEST_PKG/$cs.err
            echo "analysis: ${cs}: failed: cscout" >> $DEST_PKG/report
        fi
    done
    cd $PWD_SRC
    for i in $SYMLINKED; do
        original=$(readlink -f $i)
        original=$(basename -- "$original")
        bname=$(basename $i)
        cp $TOOL_DIR/$original.txt $TOOL_DIR/$bname.txt 2> /dev/null
        cp $TOOL_DIR/$original.cs $TOOL_DIR/$bname.cs 2> /dev/null
    done
}

main () {
    TOOL_DIR="$PWD_SRC/cscout_projects"
    init
    build
    cs_merge_files
    detect_binaries
    detect_packages
    run_cscout
    produce_callgraphs
}

main

exit 0
