#!/bin/bash
# Parameters
DSC=$1
SRC=$2

# Working directories
PWD_PKG=$(pwd)
cd $SRC
PWD_SRC=$(pwd)
cd ../

# Global variables
R_OPTION_PARAM="cgraph.txt?all=1&n=p&type=1"
NAME=$(cat $DSC | grep '^Source: ')
NAME=${NAME#"Source: "}
NAME="$(echo -e "${NAME}" | tr -d '[:space:]')"
VERSION=$(cat $DSC | grep '^Version: ')
VERSION=${VERSION#"Version: "}
VERSION="$(echo -e "${VERSION}" | tr -d '[:space:]')"
PKG="$NAME-$VERSION"

# Directories
DEST="/callgraphs/"
DEST_PKG=$DEST$PKG
CALLGRAPHS=$DEST_PKG"/callgraphs"
BINARIES_PER_PKG=$PWD_SRC/binaries_per_pkg
CS_CALLGRAPHS=$PWD_SRC/cscout_callgraphs
PACKAGES=$PWD_PKG/packages

mkdir $BINARIES_PER_PKG

# File to save status
REPORT=/callgraphs/report


NAME_T="$(cat $1 | grep 'Source: ' | cut -d ':' -f2)"
VERSION_T="$(cat $1 | grep 'Version: ' | cut -d ':' -f2)"
NAME="$(echo -e "${NAME_T}" | tr -d '[:space:]')"
VERSION="$(echo -e "${VERSION_T}" | tr -d '[:space:]')"
PKG="$NAME-$VERSION"
ERROR="$PKG.err"
cd $2
HOME_DIR=$(pwd)

BINARIES=''
SYMLINKED=''
TOTAL_BIN=''
HAS_DEBS=0

analysis() {
    FILES=$@
    extract_bc="extract-bc -b"

    for i in $FILES; do
        local name=$(basename $i)
        local directory=$(dirname $i)
        mkdir -p /callgraphs/$PKG/$directory
        # extract LLVM bitcode
        $extract_bc $i 2> error
        STATUS=$?
        if [ $STATUS != 0 ]; then
            echo "$PKG: $i extract-bc error" >> /callgraphs/report && \
                mv error /callgraphs/$PKG/$directory/$name.ext.err
        elif [ -z "$i.bc" ]; then
            echo "$PKG: $i no .bc file found" >> /callgraphs/report && \
                if [ -z "error" ]; then
                    mv error /callgraphs/$PKG/$directory/$name.ext.err
                fi
        else
            # TODO Get warnings
            wpa -fspta -dump-callgraph $i.bc 2> error
            STATUS=$?
            if [[ -f "callgraph_final.dot" ]]; then
                echo "$PKG: $i done" >> /callgraphs/report && \
                    mv callgraph_final.dot \
                        /callgraphs/$PKG/$directory/$name.dot && \
                    rm -f callgraph_initial.dot $i.bc
            elif [[ -f "error" ]]; then
                echo "$PKG: $i SVF failed" >> /callgraphs/report && \
                    mv error /callgraphs/$PKG/$directory/$name.svf.err
            fi
        fi
    done
}

run() {
    # run SVF on package
    CC=/usr/local/bin/wllvm dpkg-buildpackage -b 2>error
    STATUS=$?
    EXCECUTABLES=$(find -type f -executable -exec sh -c \
        "file -i '{}' | grep -q 'x-executable; charset=binary'" \; -print)
    ARCHIVES=$(find -type f -exec sh -c \
        "file -i '{}' | grep -q 'x-archive; charset=binary'" \; -print)
    SHAREDLIBS=$(find -type f -exec sh -c \
        "file -i '{}' | grep -q 'x-sharedlib; charset=binary'" \; -print)
    # Check if there are binaries
    if [ -z "$EXCECUTABLES" ] && [ -z "$ARCHIVES" ] && \
       [ -z "$SHAREDLIBS" ] && [ $STATUS == 0 ]; then
        echo "$PKG: no binary files found" >> /callgraphs/report && \
            exit 0
    elif [[ -f "error" ]] && [ $STATUS != 0 ]; then
        echo "$PKG: compilation failure" >> /callgraphs/report && \
            mv error /callgraphs/$ERROR && \
            rm -rf $PKG && \
            exit 0
    fi
    # Create directory to save callgraphs and errors
    mkdir -p /callgraphs/$PKG
    if [ ! -z "$EXCECUTABLES" ]; then
        analysis $EXCECUTABLES
    fi
    if [ ! -z "$ARCHIVES" ]; then
        analysis $ARCHIVES
    fi
    if [ ! -z "$SHAREDLIBS" ]; then
        analysis $SHAREDLIBS
    fi
}

prepare_env() {
    export LLVM_SRC=/usr/local/installations/llvm-7.0.0.src
    export LLVM_OBJ=/usr/lib/llvm-7/build
    export LLVM_DIR=/usr/lib/llvm-7/build
    export SVF_HOME=/usr/local/installations/SVF/
    export PATH=$SVF_HOME/Release-build/bin:$PATH
    export LLVM_COMPILER=clang
    export CFLAGS='-fPIC'
    # replace '=' and ':=' with '?=' in rules Makefile, in templates Makefiles
    sed -i -E "s/CC [:]?=/CC ?=/g" debian/rules
    sed -i -E "s/CC[:]?=/CC?=/g" debian/rules
    for i in Makefile*; do
        sed -i -E "s/CC [:]?=/CC ?=/g" $i 2> /dev/null
        sed -i -E "s/CC[:]?=/CC?=/g" $i 2> /dev/null
    done
    ln -s /usr/bin/clang-7 /usr/bin/clang
    ln -s /usr/bin/clang++-7 /usr/bin/clang++
    ln -s /usr/bin/llvm-link-7 /usr/bin/llvm-link
    ln -s /usr/local/bin/wllvm /usr/bin/wllvm
    ln -s /usr/local/bin/wllvm++ /usr/bin/wllvm++
}

build() {
    CC=/usr/bin/wllvm CXX=/usr/bin/wllvm++ dpkg-buildpackage -b 2>error
    STATUS=$?
    if [ $STATUS -ne 0 ]; then
        HAS_DEBS=$STATUS
        ./debian/rules clean && \
            CC=/usr/bin/wllvm CXX=/usr/bin/wllvm++ ./configure --prefix=$(pwd)/debian/tmp
        CC=/usr/bin/wllvm CXX=/usr/bin/wllvm++ make DESTDIR=$(pwd)/debian/tmp
        STATUS=$?
        if [ $STATUS -ne 0 ]; then
            exit -1
            # TODO add checks
        fi
    fi
}

detect_binaries() {
    printf "\n###Debug: binaries\n"
    EXCECUTABLES=$(find -type f -executable -exec sh -c \
        "file -i '{}' | grep -q 'x-executable; charset=binary'" \; -print)
    ARCHIVES=$(find -type f -exec sh -c \
        "file -i '{}' | grep -q 'x-archive; charset=binary'" \; -print)
    SHAREDLIBS=$(find -type f -exec sh -c \
        "file -i '{}' | grep -q 'x-sharedlib; charset=binary'" \; -print)
    BINARIES="${EXCECUTABLES} ${ARCHIVES} ${SHAREDLIBS}"
    SYMLINKED=$(find -type f -exec sh -c \
        "file -i '{}' | grep -q 'x-sharedlib; charset=binary'" \; -print)
    TOTAL_BIN="${$BINARIES} ${SYMLINKED}"
}

detect_packages() {
    # Keep only those inside the debian directory
    printf "\n###Debug: detect_packages\n"
    # Number of packages
    NUM=$(awk '/^Package:/{a++}END{print a}' debian/control)
    # Names of packages
    NAMES=$(grep "Package:" debian/control | cut -d ":" -f2 | awk '{$1=$1};1')
    if [ "$NUM" -gt "1" ]; then
        for n in $NAMES; do
            prefix="./debian/tmp/"
            install_file="debian/$n.install"
            if [ -f $install_file ]; then
                for path in $(cat $install_file | cut -d ' ' -f1); do
                    for f in $prefix$path; do
                        x=$(basename -- "$f")
                        if [[ "$TOTAL_BIN" == *"$x"* ]]; then
                            # It may have duplicates
                            echo "$x" >> $BINARIES_PER_PKG/$n
                        fi
                    done
                done
            fi
        done
    else
        for bin in $TOTAL_BIN; do
            x=$(basename -- "$bin")
            # It may have duplicates
            echo "$x" >> $BINARIES_PER_PKG/$NAMES
        done
    fi
}

run_svf() {
    printf "\n###Debug: run_svf\n"
    for i in $BINARIES; do
        extract-bc -b $i 2> bc_error
        # TODO check if bc exists
        wpa -fspta -dump-callgraph $i.bc 2> svf_error
        # TODO check if svf worked
        cp callgraph_final.dot $i.dot
    done
}

# If build failed we want to rebuild the project to get the .deb
rebuild() {
    echo "REBUILD"
    echo "$HAS_DEBS"
    echo "REBUILD"
    if [ $HAS_DEBS -ne 0 ]; then
        sed -i -E 's/CC \?=/CC =/g' debian/rules
        sed -i -E 's/CC\?=/CC=/g' debian/rules
        for i in Makefile*; do
            sed -i -E 's/CC \?=/CC =/g' $i 2> /dev/null
            sed -i -E 's/CC\?=/CC=/g' $i 2> /dev/null
        done
        dpkg-buildpackage -b
    fi
}

main () {
    prepare_env && build && detect_binaries && run_svf && rebuild && \
        detect_packages
    # install_deps
    # exports
    # replace_cc
    # run
}

main

exit 0
